import type { Article } from '../schema'

export const articles: Article[] = [
  {
    slug: 'canopy-cover-and-summer-surface-temperature',
    issueSlug: 'volume-1-issue-1',
    disciplineSlug: 'natural-sciences',
    disciplineName: 'Natural Sciences',
    articleType: 'Research article',
    title: 'Canopy cover and summer surface temperature in mid-sized European cities',
    abstract:
      'A comparison of thermal imagery and ground sensor readings across eleven cities, testing whether canopy targets translate into measurable cooling.',
    keywords: ['Urban climate', 'Remote sensing', 'Thermal imagery'],
    status: 'under_review',
    statusLabel: 'Under review',
    citation: 'ICRR, Vol. 1, Issue 1 (forthcoming)',
    pdfPath: null,
    pageStart: null,
    pageEnd: null,
    receivedOn: null,
    acceptedOn: null,
    publishedOn: null,
    authors: [
      {
        authorId: 'a1',
        authorName: 'Amara Okonkwo',
        authorSlug: 'amara-okonkwo',
        affiliationMarker: '1',
        order: 1,
      },
    ],
  },
  {
    slug: 'microloan-repayment-and-informal-income-volatility',
    issueSlug: 'volume-1-issue-1',
    disciplineSlug: 'business-economics',
    disciplineName: 'Business & Economics',
    articleType: 'Research article',
    title: 'Microloan repayment and informal income volatility',
    abstract:
      'Tests whether income volatility, rather than income level, predicts default among informally employed borrowers.',
    keywords: ['Household finance', 'Informal labour', 'Credit access'],
    status: 'under_review',
    statusLabel: 'Under review',
    citation: 'ICRR, Vol. 1, Issue 1 (forthcoming)',
    pdfPath: null,
    pageStart: null,
    pageEnd: null,
    receivedOn: null,
    acceptedOn: null,
    publishedOn: null,
    authors: [
      {
        authorId: 'a2',
        authorName: 'Daniel Reyes',
        authorSlug: 'daniel-reyes',
        affiliationMarker: '1',
        order: 1,
      },
    ],
  },
  {
    slug: 'letters-of-credit-and-letters-of-trust',
    issueSlug: 'volume-1-issue-1',
    disciplineSlug: 'humanities',
    disciplineName: 'Humanities',
    articleType: 'Research article',
    title: 'Letters of credit and letters of trust in the treaty ports',
    abstract:
      'Reads a corpus of merchant correspondence to trace how reputation substituted for enforceable contract.',
    keywords: ['Economic history', 'Port cities', 'Archival method'],
    status: 'under_review',
    statusLabel: 'Under review',
    citation: 'ICRR, Vol. 1, Issue 1 (forthcoming)',
    pdfPath: null,
    pageStart: null,
    pageEnd: null,
    receivedOn: null,
    acceptedOn: null,
    publishedOn: null,
    authors: [
      {
        authorId: 'a4',
        authorName: 'Kenji Watanabe',
        authorSlug: 'kenji-watanabe',
        affiliationMarker: '1',
        order: 1,
      },
    ],
  },
  {
    slug: 'perceived-and-actual-competence-in-student-project-groups',
    issueSlug: 'volume-1-issue-1',
    disciplineSlug: 'social-sciences',
    disciplineName: 'Social Sciences',
    articleType: 'Replication study',
    title: 'Perceived and actual competence in student project groups: a four-site replication',
    abstract:
      'A pre-registered replication testing whether confident speech predicts assigned credibility more strongly than demonstrated accuracy.',
    keywords: ['Group dynamics', 'Replication', 'Credibility judgement'],
    status: 'under_review',
    statusLabel: 'Under review',
    citation: 'ICRR, Vol. 1, Issue 1 (forthcoming)',
    pdfPath: null,
    pageStart: null,
    pageEnd: null,
    receivedOn: null,
    acceptedOn: null,
    publishedOn: null,
    authors: [
      {
        authorId: 'a5',
        authorName: 'Priya Nair',
        authorSlug: 'priya-nair',
        affiliationMarker: '1',
        order: 1,
      },
    ],
  },
]
