import type { Author } from '../schema'

/**
 * Placeholder profiles. They exist so the filter, search, empty state, and
 * profile route are all demonstrable before Issue 1. Replace before launch.
 */
export const authors: Author[] = [
  {
    id: 'a1',
    slug: 'amara-okonkwo',
    name: 'Amara Okonkwo',
    role: 'MSc candidate, Environmental Science',
    affiliation: 'University of Edinburgh',
    department: 'School of GeoSciences',
    location: 'Edinburgh, United Kingdom',
    disciplineSlug: 'natural-sciences',
    disciplineName: 'Natural Sciences',
    orcid: '0000-0002-1825-0097',
    bio: 'Amara studies how urban tree canopy affects summer surface temperatures in mid-sized European cities. Her work combines satellite thermal imagery with ground sensor networks, and she is interested in making municipal climate data usable by the councils that collect it.',
    interests: ['Urban climate', 'Remote sensing', 'Environmental policy', 'Open data'],
    portraitPath: null,
  },
  {
    id: 'a2',
    slug: 'daniel-reyes',
    name: 'Daniel Reyes',
    role: 'Undergraduate, Economics',
    affiliation: 'Universidad de Chile',
    department: 'Facultad de Economía y Negocios',
    location: 'Santiago, Chile',
    disciplineSlug: 'business-economics',
    disciplineName: 'Business & Economics',
    orcid: '0000-0001-5109-3700',
    bio: 'Daniel works on informal labour markets and household credit access in Latin America. He is assembling a panel dataset on microloan repayment drawn from three national household surveys.',
    interests: ['Informal labour', 'Household finance', 'Development economics'],
    portraitPath: null,
  },
  {
    id: 'a3',
    slug: 'sofia-almeida',
    name: 'Sofia Almeida',
    role: 'LLM candidate, Public Law',
    affiliation: 'Universidade de Lisboa',
    department: 'Faculdade de Direito',
    location: 'Lisbon, Portugal',
    disciplineSlug: 'law-policy',
    disciplineName: 'Law & Policy',
    orcid: '0000-0003-4471-2288',
    bio: 'Sofia researches how national courts apply proportionality review to emergency legislation, with a focus on measures introduced under time pressure and later left in force.',
    interests: ['Constitutional law', 'Proportionality', 'Emergency powers', 'Comparative law'],
    portraitPath: null,
  },
  {
    id: 'a4',
    slug: 'kenji-watanabe',
    name: 'Kenji Watanabe',
    role: 'Undergraduate, History',
    affiliation: 'University of Tokyo',
    department: 'Faculty of Letters',
    location: 'Tokyo, Japan',
    disciplineSlug: 'humanities',
    disciplineName: 'Humanities',
    orcid: '0000-0002-9931-4410',
    bio: 'Kenji works on port-city trade correspondence in the nineteenth century, reading merchant letters as evidence of how commercial trust was established between parties who never met.',
    interests: ['Economic history', 'Archival method', 'Port cities'],
    portraitPath: null,
  },
  {
    id: 'a5',
    slug: 'priya-nair',
    name: 'Priya Nair',
    role: 'PhD candidate, Social Psychology',
    affiliation: 'University of Toronto',
    department: 'Department of Psychology',
    location: 'Toronto, Canada',
    disciplineSlug: 'social-sciences',
    disciplineName: 'Social Sciences',
    orcid: '0000-0001-7742-6013',
    bio: 'Priya studies how students judge the credibility of peers in group work, and whether those judgements track actual competence. Her current project is a pre-registered replication across four institutions.',
    interests: ['Group dynamics', 'Credibility judgement', 'Replication', 'Pre-registration'],
    portraitPath: null,
  },
  {
    id: 'a6',
    slug: 'lukas-brenner',
    name: 'Lukas Brenner',
    role: 'MSc candidate, Chemistry',
    affiliation: 'ETH Zürich',
    department: 'Department of Chemistry and Applied Biosciences',
    location: 'Zürich, Switzerland',
    disciplineSlug: 'natural-sciences',
    disciplineName: 'Natural Sciences',
    orcid: '0000-0002-3308-9915',
    bio: 'Lukas develops low-cost colorimetric assays for detecting heavy metals in drinking water, with an emphasis on methods that can be run without laboratory instrumentation.',
    interests: ['Analytical chemistry', 'Water quality', 'Low-cost instrumentation'],
    portraitPath: null,
  },
]
